ColumnChart компонент all tests green
js-tasks-ru/js-20210309-2_dmitriy-glushkov pull request #4
Opened 2021-03-24 18:35 UTC by ddimasik

У меня явно ошибка с ф-ей update() и кодом, потому что она пустая, а все тесты проходят ) но я пока не понял что неправильно )

2021-03-24 18:35 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-24 21:17 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        res = res + `<div style="--value: ${this.chartHeight}" data-tooltip="100%"></div>`;
данную операцию можно сократить:
```
res += `<div style="--value: ${this.chartHeight}" data-tooltip="100%"></div>`;
```

2021-03-24 21:17 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        res = res + `<div style="--value: ${columnHeight}" data-tooltip="${tooltipValue}%"></div>`;
при построении тимплейта компонента следует отдавать предпочтение методу `map`:
```
    return data
      .map(item => {
        const percent = (item / maxValue * 100).toFixed(0);

        return `<div style="--value: ${Math.floor(item * scale)}" data-tooltip="${percent}%"></div>`;
      })
      .join('');
```
более подробно обсудим на занятии

2021-03-24 21:18 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    if (!this.data || this.data.length === 0) {
подумайте, можно ли как-то объединить эти 2 шаблона?
и избавиться от `else` секции

2021-03-24 21:19 UTC, dosandk requested changes
хорошо, но нужно попробовать избавиться от дубликатов шаблона в методе `render`

2021-03-24 21:35 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +
тест я поправлю. 
В данном методе нужно "перерисовать" значения в компоненте согласно новым входным данным. Например вызвать метод `this.pasteColumns()` и значения подставить в соответствующий элемент

2021-03-26 10:29 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    return (!this.data || this.data.length === 0) ?
можно просто убрать класс `loading` после создания тимплейта, вот так:
```
if (this.data.length) {
  this.element.classList.remove('column-chart_loading');
}
```

2021-03-26 10:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      res += `<div data-element="body" class="column-chart__chart">`;
лучше использовать метод `map` вместо конкатенации строк, более детально рассмотрим на занятии

2021-03-26 10:30 UTC, dosandk approved these changes
good 👍

2021-03-26 10:30 UTC, merged